import { ProbableQuestion } from "@/types";

export const predictedPaper: ProbableQuestion[] = [
  {
    id: "pq-1",
    section: "A",
    text: "Define a process. How is it different from a program?",
    topic: "Process Concept",
    unit: "Unit II",
    frequency: 6,
    syllabusRelevance: "high",
    patternScore: "high",
    marks: 2,
  },
  {
    id: "pq-2",
    section: "A",
    text: "State the necessary conditions for a deadlock to occur.",
    topic: "Deadlock",
    unit: "Unit III",
    frequency: 5,
    syllabusRelevance: "high",
    patternScore: "high",
    marks: 2,
  },
  {
    id: "pq-3",
    section: "A",
    text: "Differentiate between paging and segmentation.",
    topic: "Memory Management",
    unit: "Unit IV",
    frequency: 3,
    syllabusRelevance: "medium",
    patternScore: "medium",
    marks: 2,
  },
  {
    id: "pq-4",
    section: "B",
    text: "Explain the Shortest Job First and Round Robin scheduling algorithms with a worked example.",
    topic: "Process Scheduling",
    unit: "Unit II",
    frequency: 8,
    syllabusRelevance: "high",
    patternScore: "high",
    marks: 5,
  },
  {
    id: "pq-5",
    section: "B",
    text: "Describe the Banker's Algorithm for deadlock avoidance with an example.",
    topic: "Deadlock",
    unit: "Unit III",
    frequency: 6,
    syllabusRelevance: "high",
    patternScore: "high",
    marks: 5,
  },
  {
    id: "pq-6",
    section: "B",
    text: "Explain any two page replacement algorithms and compare their performance.",
    topic: "Page Replacement",
    unit: "Unit IV",
    frequency: 4,
    syllabusRelevance: "medium",
    patternScore: "medium",
    marks: 5,
  },
  {
    id: "pq-7",
    section: "C",
    text: "Discuss process synchronization problems. Solve the Producer-Consumer problem using semaphores.",
    topic: "Semaphores",
    unit: "Unit III",
    frequency: 5,
    syllabusRelevance: "high",
    patternScore: "high",
    marks: 10,
  },
  {
    id: "pq-8",
    section: "C",
    text: "Explain the file allocation methods in operating systems with their advantages and limitations.",
    topic: "File Systems",
    unit: "Unit V",
    frequency: 3,
    syllabusRelevance: "medium",
    patternScore: "low",
    marks: 10,
  },
];
