import { Subject } from "@/types";

export const subjects: Subject[] = [
  {
    id: "os",
    name: "Operating Systems",
    code: "PCC-CS501",
    semester: 5,
    program: "B.Tech CSE",
    university: "MAKAUT",
    preparation: 72,
    color: "#C1791F",
    units: [
      { id: "os-u1", name: "Operating System Overview", progress: 90 },
      { id: "os-u2", name: "Process Management", progress: 75 },
      { id: "os-u3", name: "Process Synchronization", progress: 55 },
      { id: "os-u4", name: "Memory Management", progress: 40 },
      { id: "os-u5", name: "File Systems", progress: 30 },
    ],
    strongTopics: ["Process Management", "CPU Scheduling", "System Calls"],
    weakTopics: ["Deadlock", "Page Replacement", "Disk Scheduling"],
  },
  {
    id: "cn",
    name: "Computer Networks",
    code: "PCC-CS502",
    semester: 5,
    program: "B.Tech CSE",
    university: "MAKAUT",
    preparation: 58,
    color: "#3F7D58",
    units: [
      { id: "cn-u1", name: "Network Fundamentals", progress: 85 },
      { id: "cn-u2", name: "Data Link Layer", progress: 62 },
      { id: "cn-u3", name: "Network Layer & Routing", progress: 48 },
      { id: "cn-u4", name: "Transport Layer", progress: 40 },
      { id: "cn-u5", name: "Application Layer", progress: 55 },
    ],
    strongTopics: ["OSI Model", "IP Addressing"],
    weakTopics: ["Routing Algorithms", "Congestion Control"],
  },
  {
    id: "dbms",
    name: "Database Management Systems",
    code: "PCC-CS503",
    semester: 5,
    program: "B.Tech CSE",
    university: "MAKAUT",
    preparation: 81,
    color: "#1B2430",
    units: [
      { id: "dbms-u1", name: "Introduction & ER Model", progress: 95 },
      { id: "dbms-u2", name: "Relational Model & SQL", progress: 88 },
      { id: "dbms-u3", name: "Normalization", progress: 82 },
      { id: "dbms-u4", name: "Transactions & Concurrency", progress: 65 },
      { id: "dbms-u5", name: "Indexing & File Organization", progress: 60 },
    ],
    strongTopics: ["DBMS Normalization", "SQL Queries", "ER Diagrams"],
    weakTopics: ["Concurrency Control", "Recovery Techniques"],
  },
  {
    id: "cs",
    name: "Cyber Security",
    code: "PEC-CS701",
    semester: 7,
    program: "B.Tech CSE",
    university: "MAKAUT",
    preparation: 45,
    color: "#B23A2E",
    units: [
      { id: "cs-u1", name: "Security Fundamentals", progress: 70 },
      { id: "cs-u2", name: "Cryptography", progress: 35 },
      { id: "cs-u3", name: "Network Security", progress: 40 },
      { id: "cs-u4", name: "Web & Application Security", progress: 38 },
      { id: "cs-u5", name: "Security Policies & Compliance", progress: 42 },
    ],
    strongTopics: ["Security Fundamentals", "Access Control"],
    weakTopics: ["Cryptography", "Compiler Design", "Malware Analysis"],
  },
  {
    id: "oop",
    name: "Object Oriented Programming",
    code: "PCC-CS402",
    semester: 4,
    program: "B.Tech CSE",
    university: "MAKAUT",
    preparation: 88,
    color: "#8F5613",
    units: [
      { id: "oop-u1", name: "OOP Foundations", progress: 96 },
      { id: "oop-u2", name: "Inheritance & Polymorphism", progress: 90 },
      { id: "oop-u3", name: "Exception Handling", progress: 84 },
      { id: "oop-u4", name: "Templates & Generics", progress: 80 },
      { id: "oop-u5", name: "File Handling & STL", progress: 78 },
    ],
    strongTopics: ["Inheritance", "Polymorphism", "Exception Handling"],
    weakTopics: ["Templates", "Operator Overloading"],
  },
  {
    id: "coa",
    name: "Computer Organization",
    code: "PCC-CS401",
    semester: 4,
    program: "B.Tech CSE",
    university: "MAKAUT",
    preparation: 66,
    color: "#5A5E68",
    units: [
      { id: "coa-u1", name: "Digital Logic Basics", progress: 80 },
      { id: "coa-u2", name: "Instruction Set & Addressing", progress: 70 },
      { id: "coa-u3", name: "CPU Architecture", progress: 60 },
      { id: "coa-u4", name: "Memory Hierarchy", progress: 55 },
      { id: "coa-u5", name: "I/O Organization", progress: 50 },
    ],
    strongTopics: ["Digital Logic", "Instruction Formats"],
    weakTopics: ["Pipelining", "Cache Mapping"],
  },
  {
    id: "dsa",
    name: "Data Structures",
    code: "PCC-CS301",
    semester: 3,
    program: "B.Tech CSE",
    university: "MAKAUT",
    preparation: 79,
    color: "#3F7D58",
    units: [
      { id: "dsa-u1", name: "Arrays & Linked Lists", progress: 92 },
      { id: "dsa-u2", name: "Stacks & Queues", progress: 88 },
      { id: "dsa-u3", name: "Trees", progress: 74 },
      { id: "dsa-u4", name: "Graphs", progress: 62 },
      { id: "dsa-u5", name: "Sorting & Hashing", progress: 70 },
    ],
    strongTopics: ["Linked Lists", "Stacks & Queues"],
    weakTopics: ["Graph Algorithms", "AVL Trees"],
  },
];

export function getSubject(id: string): Subject | undefined {
  return subjects.find((s) => s.id === id);
}
